name: nbprov-demo
channels:
  - defaults
dependencies:
  - python=3.8.5
  - jupyterlab=2.2.6
  - nodejs=10.13.0
  - numpy=1.19.2
  - pandas=1.1.3
  - matplotlib=3.3.2
  - seaborn=0.11.0
  - vega_datasets=0.7.0
  - altair=4.1.0
  - scipy=1.5.2
  - scikit-learn=0.23.2
